language: python
python:
  - "3.6"

cache: pip

env:
  global:
 - CODECOV_TOKEN="06154fdb-53ed-44a5-880b-64be61c02af8"

install:
  - "pip install -r requirements.txt"

branches:
  only:
  - develop

script:
  - "nosetests --with-coverage --cover-package=api"
   
after_success:
  - coveralls
  - codecov