language: python
python:
  - "3.6"

cache: pip

env:
  global:


install:
  - "pip install -r requirements.txt"

branches:
  only:
  - gh-pages
  - /.*/

script:
  - "nosetests --with-coverage --cover-package=api"
  - "coverage report"
after_success:
  - coveralls
  - codecov