language: python
python:
 - "3.6"

services:
 - postgresql

env:
 global:
   - APP_SETTINGS="testing"
   - CODECOV_TOKEN="06154fdb-53ed-44a5-880b-64be61c02af8"

install:
 - "pip install -r requirements.txt"
 - "pip install coveralls"

before_script:
 - psql -c "CREATE ROLE codjoe WITH SUPERUSER LOGIN PASSWORD 'codjoe';" -U postgres
 - psql -c "CREATE DATABASE test_db;" -U postgres

script:
 - "nosetests --with-coverage --cover-package=APIs"
   
after_success:
 - coveralls
 - codecov